fix: Fix libexec/texenv-repo

diff --git a/libexec/texenv-repo b/libexec/texenv-repo
--- a/libexec/texenv-repo
+++ b/libexec/texenv-repo
@@ -89,6 +89,10 @@ cmdRepo() {
   else
     VERSION_YEAR="$(${executeRun} tlmgr --version | awk 'END{print $5}')"
     CURRENT_YEAR="$(date +%Y)"
+    [[ -z "${VERSION_YEAR}" ]] && {
+      builtin echo "texenv: failed to determine TeX Live version year" >&2
+      exit 1
+    }
     if [[ "${VERSION_YEAR:-}" == "${CURRENT_YEAR}" ]]; then
       REPO="https://ctan.math.illinois.edu/systems/texlive/tlnet"
       [[ "${REPO}" == "${CURRENT_REPO}" ]] && {
