fix: Fix libexec/texenv*

diff --git a/libexec/texenv-exec b/libexec/texenv-exec
--- a/libexec/texenv-exec
+++ b/libexec/texenv-exec
@@ -13,7 +13,13 @@ cmdExec() {
   declare SCRIPT_NAME
   SCRIPT_NAME="${0##*/}"
   libs="$(type -P "texenv-libs" || true)"
+  cmdRepo="$(type -P "texenv-repo" || true)"
+  cmdRehash="$(type -P "texenv-rehash" || true)"
   executeRun="${libs} executeRun"
+  [[ -z "${executeRun}" || -z "${cmdRepo}" || -z "${cmdRehash}" ]] && {
+    builtin echo "texenv: required component(s) missing" >&2
+    exit 1
+  }
   case "${1:-}" in
     -h | --help)
       builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} <cmd> [args]"
@@ -27,7 +33,6 @@ cmdExec() {
     if [[ "${1:-}" == "tlmgr" ]]; then
       case "${2:-}" in
         install | update | info | search)
-          cmdRepo="$(type -P "texenv-repo" || true)"
           "${cmdRepo}" > /dev/null
           ;;
       esac
@@ -38,7 +43,6 @@ cmdExec() {
     if [[ "${1:-}" == "tlmgr" ]]; then
       case "${2:-}" in
         install | update | uninstall | remove)
-          cmdRehash="$(type -P "texenv-rehash" || true)"
           "${cmdRehash}"
           ;;
       esac
diff --git a/libexec/texenv-version b/libexec/texenv-version
--- a/libexec/texenv-version
+++ b/libexec/texenv-version
@@ -10,7 +10,13 @@ cmdVersion() {
   declare VERSION_PATH
   declare TEX_VERSION_INFO
   declare SCRIPT_NAME
+  declare libs
   SCRIPT_NAME="${0##*/}"
+  libs="$(type -P "texenv-libs" || true)"
+  [[ -z "${libs}" ]] && {
+    builtin echo "texenv: required component(s) missing" >&2
+    exit 1
+  }
   case "${1:-}" in
     -h | --help)
       builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} [options]"
@@ -21,7 +27,7 @@ cmdVersion() {
       ;;
   esac
   if [[ -d "${TEXENV_VERSIONS}" ]]; then
-    TEX_VERSION_INFO="$("$(type -P "texenv-libs" || true)" resolveVersion || true)"
+    TEX_VERSION_INFO="$("${libs}" resolveVersion || true)"
     VERSION="$(awk -F": " '/TinyTeX-Version: /{print $2}' <<< "${TEX_VERSION_INFO}")"
     VERSION_PATH="$(awk -F": " '/TinyTeX-Path: /{print $2}' <<< "${TEX_VERSION_INFO}")"
     [[ -z "${VERSION}" || -z "${VERSION_PATH}" ]] && {
diff --git a/libexec/texenv-versions b/libexec/texenv-versions
--- a/libexec/texenv-versions
+++ b/libexec/texenv-versions
@@ -11,7 +11,13 @@ cmdVersions() {
   declare TEX_VERSION_INFO
   declare VERSIONS
   declare SCRIPT_NAME
+  declare libs
   SCRIPT_NAME="${0##*/}"
+  libs="$(type -P "texenv-libs" || true)"
+  [[ -z "${libs}" ]] && {
+    builtin echo "texenv: required component(s) missing" >&2
+    exit 1
+  }
   case "${1:-}" in
     -h | --help)
       builtin echo "Usage: ${SCRIPT_NAME%%-*} ${SCRIPT_NAME##*-} [options]"
@@ -22,7 +28,7 @@ cmdVersions() {
       ;;
   esac
   if [[ -d "${TEXENV_VERSIONS}" ]]; then
-    TEX_VERSION_INFO="$("$(type -P "texenv-libs" || true)" resolveVersion || true)"
+    TEX_VERSION_INFO="$("${libs}" resolveVersion || true)"
     VERSION="$(awk -F": " '/TinyTeX-Version: /{print $2}' <<< "${TEX_VERSION_INFO}")"
     VERSION_PATH="$(awk -F": " '/TinyTeX-Path: /{print $2}' <<< "${TEX_VERSION_INFO}")"
     VERSIONS="$(find "${TEXENV_VERSIONS}" -maxdepth 1 ! -name "${TEXENV_VERSIONS##*/}" -type d)"
