fix: Fix libexec/texenv

diff --git a/libexec/texenv b/libexec/texenv
--- a/libexec/texenv
+++ b/libexec/texenv
@@ -83,7 +83,7 @@ executeRun() {
       exit 1
     }
     export TEXMFHOME="${TEXMF_HOME}"
-    exec "${CMD_PATH}" "${@}"
+    "${CMD_PATH}" "${@}"
   }
 }
 
@@ -108,8 +108,8 @@ cmdInit() {
 # Rebuild shims for installed TeX Live versions
 cmdRehash() {
   {
-    rm -rf "${TEXENV_SHIMS:?}"/*
-    find "${TEXENV_VERSIONS}" -path "*/bin/${PLATFORM}/*" ! -type d \
+    rm -rf "${TEXENV_SHIMS:?}"/* && \
+    find "${TEXENV_VERSIONS}" -path "*/bin/${PLATFORM}/*" ! -type d -exec test -e {} \; -print \
       | awk -F/ '!a[$NF]++{print $NF}' \
       | while read -r CMD; do
           local SHIM_PATH="${TEXENV_SHIMS}/${CMD}"
@@ -123,7 +123,7 @@ cmdRehash() {
             builtin echo "  exec \"\${CMD_PATH}/texenv\" exec \"\${CMD_NAME}\" \"\${@}\""
             builtin echo "}"
             builtin echo "shim \"\${@}\""
-          } > "${SHIM_PATH}"
+          } > "${SHIM_PATH}" && \
           chmod +x "${SHIM_PATH}"
         done
   } || {
@@ -176,17 +176,17 @@ cmdInstall() {
     exit 1
   }
   {
-    echo "Installing TeX Live version ${VERSION}..."
-    mkdir -p "${TEX_DIR}"
-    curl -L -f --retry 10 --retry-delay 30 -# "${TEX_URL}" -o "${TEX_TMP}"
-    tar xf "${TEX_TMP}" -C "${TEX_DIR}" --strip-components=1
-    rm -rf "${TEX_TMP}"
-    cmdRehash
+    echo "Installing TeX Live version ${VERSION}..." && \
+    mkdir -p "${TEX_DIR}" && \
+    curl -L -f --retry 10 --retry-delay 30 -# "${TEX_URL}" -o "${TEX_TMP}" && \
+    tar xf "${TEX_TMP}" -C "${TEX_DIR}" --strip-components=1 && \
+    rm -rf "${TEX_TMP}" && \
+    cmdRehash && \
     echo "TeX Live version ${VERSION} installed successfully."
   } || {
-    rm -rf "${TEX_DIR:?}"
-    rm -rf "${TEX_TMP:?}"
-    echo "texenv: failed to install version ${VERSION}" >&2
+    rm -rf "${TEX_DIR:?}" && \
+    rm -rf "${TEX_TMP:?}" && \
+    echo "texenv: failed to install version ${VERSION}" >&2 && \
     exit 1
   }
 }
@@ -325,13 +325,23 @@ cmdRepo() {
 
 # Execute command in current TeX Live version
 cmdExec(){
-  if [[ "${1:-}" == "tlmgr" ]]; then
-    case "${2:-}" in
-      install|update|info|search)
-        cmdRepo > /dev/null;;
-    esac
-  fi
-  executeRun "${@}"
+  {
+    if [[ "${1:-}" == "tlmgr" ]]; then
+      case "${2:-}" in
+        install|update|info|search)
+          cmdRepo > /dev/null;;
+      esac
+    fi
+  } && {
+    executeRun "${@}"
+  } && {
+    if [[ "${1:-}" == "tlmgr" ]]; then
+      case "${2:-}" in
+        install|update|uninstall|remove)
+          cmdRehash;;
+      esac
+    fi
+  }
 }
 
 # Freeze TeX packages to requirements file
